# fly.toml app configuration file generated for host-langflow-2zwsdw on 2025-07-06T07:42:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'host-langflow-2zwsdw'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
